name: example-repo
models:
  addsub:
    backend: onnxruntime
    versions:
      - artifact_uri: s3://test-bucket/onnx/model.onnx
    test_cases:
      - inputs:
          a:
            data: [1.0, 2.0, 3.0]
            dtype: float32
            dims: [1, 3]
          b:
            data: [4.0, 5.0, 6.0]
            dtype: float32
            dims: [1, 3]
        expected_outputs:
          add:
            data: [5.0, 7.0, 9.0]
            dtype: float32
            dims: [1, 3]
          sub:
            data: [-3.0, -3.0, -3.0]
            dtype: float32
            dims: [1, 3]
